### ISSUE TITLE
1.2: Test Explorer integration

### ISSUE THREAD

**Issue by sirredbeard** [WhitewaterFoundry/wlinux-setup#35]
"I've been running into issues when running explorer.sh in that it seems to install fine, but clicking on the menu entry gives an error (will update this with exact error). I have implemented a new function in common.sh that finds the exact distribution executable name, so that explorer.sh can be distribution agnostic going into the future. But if this turns out to be causing too many issues can stick this on the back-burner for now." - @grufwub

**Comment by grufwub** [comment]
Handled #43 :+1:
