### ISSUE TITLE
1.2: Elegant handle upgrade of wlinux-setup.

### ISSUE THREAD

**Issue by sirredbeard** [WhitewaterFoundry/wlinux-setup#39]
"Add code to put wlinux-setup on apt-mark hold when running the 'wlinux-setup' executable then remove hold after + error checking code to ensure a failed shutdown previously hasn't left it in a 'held' state accidentally. Otherwise when running updateupgrade function within install scripts we might run into odd situation where we upgrade the wlinux-seutp package while in-use. We can add code in wlinux-base to place a marker file that wlinux-setup looks for on each start, indicating that there is an update available and prompt the user. Same goes for for us changing sources.list or general upstream changes so we can prompt the user that dist-upgrade is available." @grufwub

**Comment by sirredbeard** [comment]
What if we ran:
```
apt-mark hold wlinux-setup
apt update
apt upgrade
apt-mark unhold wlinux-setup
```

**Comment by grufwub** [comment]
Handled here: #45 if you'd like to check out and see what you think :)
